import yaml
import os.path
from pathlib import Path
from scripts.common_functions import parse_region
import sys
import json


# The match ancestors step requires as much rescursion as
# there are ancestor groups
sys.setrecursionlimit(10000)


configfile: "config.yaml"


shell.prefix(config["prefix"])

with open(os.path.join("workflow", "resources.yaml"), "r") as resource_file:
    resources_config = yaml.safe_load(resource_file)


def get_resource(rule_name, resource_type):
    if rule_name in resources_config and resource_type in resources_config[rule_name]:
        return resources_config[rule_name][resource_type]
    else:
        return resources_config["default"][resource_type]


data_dir = Path(config["data_dir"])


# These are quick steps that we don't want to submit jobs for
localrules:
    all,
    summary_table,


def ds_dir(wildcards):
    if hasattr(wildcards, "region_name"):
        chr = parse_region(config["regions"][wildcards.region_name])[0]
    else:
        chr = wildcards.chrom_num
    return data_dir / "zarr_vcfs" / f"chr{chr}" / "data.zarr"


rule all:
    input:
        expand(
            data_dir / "{subset_name}-{filter_set}-region_summary_table.csv",
            subset_name=config["sample_subsets"].keys(),
            filter_set=config["filters"].keys(),
        ),
        expand(
            data_dir
            / "trees"
            / "{subset_name}-{region_name}-{filter_set}"
            / "{subset_name}-{region_name}-{filter_set}-truncate-{truncation}-mm{mismatch}-post-processed-simplified-SDN-dated-{mut_rate}.trees",
            subset_name=config["sample_subsets"].keys(),
            region_name=config["regions"].keys(),
            filter_set=config["filters"].keys(),
            mismatch=config["mismatch_values"],
            truncation=[
                f"{c['lower']}-{c['upper']}-{c['multiplier']}"
                for c in config["truncate"]
            ],
            mut_rate=[f"{c['mutation_rate']}" for c in config["tsdate"]],
        ),


checkpoint bio2zarr_dexplode_init:
    input:
        vcf=lambda wildcards: config["vcf"].format(chrom=wildcards.chrom_num),
        tbi=lambda wildcards: config["vcf"].format(chrom=wildcards.chrom_num) + ".tbi",
    output:
        data_dir / "exploded_vcfs_md" / "chr{chrom_num}.metadata.json",
    params:
        zarr_dir=str(data_dir / "exploded_vcfs" / "chr{chrom_num}"),
        num_partitions=config["bio2zarr"]["num_partitions"],
    threads: get_resource("bio2zarr_dexplode_init", "threads")
    resources:
        mem_mb=get_resource("bio2zarr_dexplode_init", "mem_mb"),
        time_min=get_resource("bio2zarr_dexplode_init", "time_min"),
        runtime=get_resource("bio2zarr_dexplode_init", "time_min"),
    conda:
        "tskit_reqs.yaml"
    shell:
        """
mkdir -p {params.zarr_dir}
python -m bio2zarr vcf2zarr dexplode-init --json --force --num-partitions {params.num_partitions} {input.vcf} {params.zarr_dir} > {output[0]}
"""


rule bio2zarr_dexplode_partition:
    input:
        data_dir / "exploded_vcfs_md" / "chr{chrom_num}.metadata.json",
    output:
        data_dir / "exploded_vcfs" / "chr{chrom_num}" / ".done_{partition}",
    params:
        outpath=lambda wildcards, output: str(Path(output[0]).parent).format(
            chrom_num=wildcards.chrom_num
        ),
    threads: get_resource("bio2zarr_dexplode_partition", "threads")
    resources:
        mem_mb=get_resource("bio2zarr_dexplode_partition", "mem_mb"),
        time_min=get_resource("bio2zarr_dexplode_partition", "time_min"),
        runtime=get_resource("bio2zarr_dexplode_partition", "time_min"),
    conda:
        "tskit_reqs.yaml"
    shell:
        """
python -m bio2zarr vcf2zarr dexplode-partition {params.outpath} {wildcards.partition} && touch {output[0]}
"""


def dexplode_partitions(wildcards):
    import json

    checkpoint_output = checkpoints.bio2zarr_dexplode_init.get(
        chrom_num=wildcards.chrom_num
    )
    with open(checkpoint_output.output[0], "r") as f:
        md = json.load(f)
    return [
        data_dir / "exploded_vcfs" / f"chr{wildcards.chrom_num}" / f".done_{p}"
        for p in range(md["num_partitions"])
    ]


rule bio2zarr_dexplode_finalise:
    input:
        dexplode_partitions,
    output:
        data_dir / "exploded_vcfs" / "chr{chrom_num}" / ".done",
    params:
        outpath=lambda wildcards, output: str(Path(output[0]).parent).format(
            chrom_num=wildcards.chrom_num
        ),
    threads: get_resource("bio2zarr_dexplode_finalise", "threads")
    resources:
        mem_mb=get_resource("bio2zarr_dexplode_finalise", "mem_mb"),
        time_min=get_resource("bio2zarr_dexplode_finalise", "time_min"),
        runtime=get_resource("bio2zarr_dexplode_finalise", "time_min"),
    conda:
        "tskit_reqs.yaml"
    shell:
        """
python -m bio2zarr vcf2zarr dexplode-finalise {params.outpath} && touch {output[0]}
"""


rule bio2zarr_mkschema:
    input:
        data_dir / "exploded_vcfs" / "chr{chrom_num}" / ".done",
    output:
        data_dir / "zarr_vcfs_schema" / "chr{chrom_num}" / "schema.json",
    params:
        inpath=lambda wildcards, input: str(Path(input[0]).parent).format(
            chrom_num=wildcards.chrom_num
        ),
    threads: get_resource("bio2zarr_mkschema", "threads")
    resources:
        mem_mb=get_resource("bio2zarr_mkschema", "mem_mb"),
        time_min=get_resource("bio2zarr_mkschema", "time_min"),
        runtime=get_resource("bio2zarr_mkschema", "time_min"),
    conda:
        "tskit_reqs.yaml"
    shell:
        """
mkdir -p {params.inpath}
python -m bio2zarr vcf2zarr mkschema {params.inpath} > {output[0]}
"""


checkpoint bio2zarr_dencode_init:
    input:
        data_dir / "exploded_vcfs" / "chr{chrom_num}" / ".done",
        data_dir / "zarr_vcfs_schema" / "chr{chrom_num}" / "schema.json",
    output:
        json=data_dir / "zarr_vcfs_md" / "chr{chrom_num}.metadata.json",
    params:
        inpath=lambda wildcards, input: str(Path(input[0]).parent).format(
            chrom_num=wildcards.chrom_num
        ),
        num_partitions=config["bio2zarr"]["num_partitions"],
        var_chunk_size=config["bio2zarr"]["variants_chunk_size"],
        datapath=str(data_dir / "zarr_vcfs" / "chr{chrom_num}" / "data.zarr"),
    threads: get_resource("bio2zarr_dencode_init", "threads")
    resources:
        mem_mb=get_resource("bio2zarr_dencode_init", "mem_mb"),
        time_min=get_resource("bio2zarr_dencode_init", "time_min"),
        runtime=get_resource("bio2zarr_dencode_init", "time_min"),
    conda:
        "tskit_reqs.yaml"
    shell:
        """
mkdir -p {params.datapath}
python -m bio2zarr vcf2zarr dencode-init --json --force \\
  --num-partitions {params.num_partitions} \\
  --variants-chunk-size {params.var_chunk_size} \\
  {params.inpath} {params.datapath} > {output.json}
"""


def dencode_partitions(wildcards):
    import json

    checkpoint_output = checkpoints.bio2zarr_dencode_init.get(
        chrom_num=wildcards.chrom_num
    )
    with open(checkpoint_output.output[0], "r") as f:
        md = json.load(f)
    return [ds_dir(wildcards) / f".done_{p}" for p in range(md["num_partitions"])]


rule bio2zarr_dencode_partition:
    input:
        data_dir / "zarr_vcfs_md" / "chr{chrom_num}.metadata.json",
    output:
        data_dir / "zarr_vcfs" / "chr{chrom_num}" / "data.zarr" / ".done_{partition}",
    params:
        outpath=lambda wildcards, output: str(Path(output[0]).parent).format(
            chrom_num=wildcards.chrom_num, partition=wildcards.partition
        ),
    threads: get_resource("bio2zarr_dencode_partition", "threads")
    resources:
        mem_mb=get_resource("bio2zarr_dencode_partition", "mem_mb"),
        time_min=get_resource("bio2zarr_dencode_partition", "time_min"),
        runtime=get_resource("bio2zarr_dencode_partition", "time_min"),
    conda:
        "tskit_reqs.yaml"
    shell:
        """
python -m bio2zarr vcf2zarr dencode-partition {params.outpath} {wildcards.partition} && touch {output[0]}
"""


rule bio2zarr_dencode_finalise:
    input:
        dencode_partitions,
    output:
        data_dir / "zarr_vcfs" / "chr{chrom_num}" / "data.zarr" / ".vcf_done",
    threads: get_resource("bio2zarr_dencode_finalise", "threads")
    resources:
        mem_mb=get_resource("bio2zarr_dencode_finalise", "mem_mb"),
        time_min=get_resource("bio2zarr_dencode_finalise", "time_min"),
        runtime=get_resource("bio2zarr_dencode_finalise", "time_min"),
    params:
        outpath=lambda wildcards, output: str(Path(output[0]).parent).format(
            chrom_num=wildcards.chrom_num
        ),
    conda:
        "tskit_reqs.yaml"
    shell:
        """
python -m bio2zarr vcf2zarr dencode-finalise {params.outpath} && touch {output[0]}
# Remove the metadata files so thaat we can write extra arrays later without updating it.
rm -rf {params.outpath}/.zmetadata*
touch {output[0]}
"""


rule load_ancestral_fasta:
    input:
        lambda wildcards: config["ancestral_fasta"].format(chrom=wildcards.chrom_num),
        data_dir / "zarr_vcfs" / "chr{chrom_num}" / "data.zarr" / ".vcf_done",
    output:
        directory(
            data_dir
            / "zarr_vcfs"
            / "chr{chrom_num}"
            / "data.zarr"
            / "variant_ancestral_allele"
        ),
        directory(
            data_dir
            / "zarr_vcfs"
            / "chr{chrom_num}"
            / "data.zarr"
            / "variant_low_quality_ancestral_allele_mask"
        ),
    threads: get_resource("load_ancestral_fasta", "threads")
    resources:
        mem_mb=get_resource("load_ancestral_fasta", "mem_mb"),
        time_min=get_resource("load_ancestral_fasta", "time_min"),
        runtime=get_resource("load_ancestral_fasta", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_load_ancestral_fasta.py"


rule pre_subset_filters:
    input:
        lambda wildcards: ds_dir(wildcards) / ".vcf_done",
        lambda wildcards: ds_dir(wildcards) / "variant_ancestral_allele",
        lambda wildcards: ds_dir(wildcards)
        / "variant_low_quality_ancestral_allele_mask",
    output:
        directory(
            data_dir
            / "zarr_vcfs"
            / "chr{chrom_num}"
            / "data.zarr"
            / "variant_bad_ancestral_mask"
        ),
        directory(
            data_dir
            / "zarr_vcfs"
            / "chr{chrom_num}"
            / "data.zarr"
            / "variant_duplicate_position_mask"
        ),
        directory(
            data_dir
            / "zarr_vcfs"
            / "chr{chrom_num}"
            / "data.zarr"
            / "variant_not_biallelic_mask"
        ),
        directory(
            data_dir
            / "zarr_vcfs"
            / "chr{chrom_num}"
            / "data.zarr"
            / "variant_not_snps_mask"
        ),
        directory(
            data_dir
            / "zarr_vcfs"
            / "chr{chrom_num}"
            / "data.zarr"
            / "variant_no_ancestral_allele_mask"
        ),
    threads: get_resource("pre_subset_filters", "threads")
    resources:
        mem_mb=get_resource("pre_subset_filters", "mem_mb"),
        time_min=get_resource("pre_subset_filters", "time_min"),
        runtime=get_resource("pre_subset_filters", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_pre_subset_filters.py"


rule region_mask:
    input:
        lambda wildcards: ds_dir(wildcards) / ".vcf_done",
    output:
        directory(
            data_dir
            / "zarr_vcfs"
            / "chr{chrom_num}"
            / "data.zarr"
            / "variant_{region_name}_region_mask"
        ),
    threads: get_resource("region_mask", "threads")
    resources:
        mem_mb=get_resource("region_mask", "mem_mb"),
        time_min=get_resource("region_mask", "time_min"),
        runtime=get_resource("region_mask", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_region_mask.py"


rule sample_mask:
    input:
        lambda wildcards: ds_dir(wildcards) / ".vcf_done",
        lambda wildcards: config["sample_subsets"][wildcards.subset_name],
    output:
        directory(
            data_dir
            / "zarr_vcfs"
            / "chr{chrom_num}"
            / "data.zarr"
            / "sample_{subset_name}_subset_mask"
        ),
    threads: get_resource("sample_mask", "threads")
    resources:
        mem_mb=get_resource("sample_mask", "mem_mb"),
        time_min=get_resource("sample_mask", "time_min"),
        runtime=get_resource("sample_mask", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_sample_mask.py"


rule allele_counts:
    input:
        lambda wildcards: ds_dir(wildcards) / ".vcf_done",
        lambda wildcards: ds_dir(wildcards) / "sample_{subset_name}_subset_mask",
        lambda wildcards: ds_dir(wildcards) / "variant_ancestral_allele",
    output:
        directory(
            data_dir
            / "zarr_vcfs"
            / "chr{chrom_num}"
            / "data.zarr"
            / "variant_{subset_name}_subset_ref_count"
        ),
        directory(
            data_dir
            / "zarr_vcfs"
            / "chr{chrom_num}"
            / "data.zarr"
            / "variant_{subset_name}_subset_ancestral_count"
        ),
        directory(
            data_dir
            / "zarr_vcfs"
            / "chr{chrom_num}"
            / "data.zarr"
            / "variant_{subset_name}_subset_missing_count"
        ),
        directory(
            data_dir
            / "zarr_vcfs"
            / "chr{chrom_num}"
            / "data.zarr"
            / "variant_{subset_name}_subset_derived_count"
        ),
    threads: get_resource("allele_counts", "threads")
    resources:
        mem_mb=get_resource("allele_counts", "mem_mb"),
        time_min=get_resource("allele_counts", "time_min"),
        runtime=get_resource("allele_counts", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_allele_counts.py"


rule subset_filters:
    input:
        lambda wildcards: ds_dir(wildcards) / ".vcf_done",
        lambda wildcards: expand(
            ds_dir(wildcards) / "{array_name}",
            array_name=[
                "variant_bad_ancestral_mask",
                "variant_no_ancestral_allele_mask",
                "variant_not_biallelic_mask",
                "variant_duplicate_position_mask",
                "variant_not_snps_mask",
                "variant_low_quality_ancestral_allele_mask",
                "variant_{subset_name}_subset_ref_count",
                "variant_{subset_name}_subset_ancestral_count",
                "variant_{subset_name}_subset_missing_count",
                "variant_{subset_name}_subset_derived_count",
                "sample_{subset_name}_subset_mask",
            ],
        ),
    output:
        data_dir
        / "zarr_vcfs"
        / "chr{chrom_num}"
        / "data.zarr"
        / ".{subset_name}_subset_{filter_set}_filters_done",
    threads: get_resource("subset_filters", "threads")
    resources:
        mem_mb=get_resource("subset_filters", "mem_mb"),
        time_min=get_resource("subset_filters", "time_min"),
        runtime=get_resource("subset_filters", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_subset_filters.py"


rule site_density_mask:
    input:
        lambda wildcards: ds_dir(wildcards) / ".vcf_done",
        lambda wildcards: ds_dir(wildcards)
        / ".{subset_name}_subset_{filter_set}_filters_done",
        lambda wildcards: ds_dir(wildcards) / "variant_{region_name}_region_mask",
    output:
        data_dir
        / "zarr_vcfs"
        / "chr{chrom_num}"
        / "data.zarr"
        / ".{subset_name}_subset_{region_name}_region_{filter_set}_site_density_mask_done",
    threads: get_resource("site_density_mask", "threads")
    resources:
        mem_mb=get_resource("site_density_mask", "mem_mb"),
        time_min=get_resource("site_density_mask", "time_min"),
        runtime=get_resource("site_density_mask", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_site_density_mask.py"


rule combined_mask:
    input:
        lambda wildcards: ds_dir(wildcards) / ".vcf_done",
        lambda wildcards: ds_dir(wildcards)
        / ".{subset_name}_subset_{filter_set}_filters_done",
        lambda wildcards: ds_dir(wildcards)
        / ".{subset_name}_subset_{region_name}_region_{filter_set}_site_density_mask_done",
        lambda wildcards: expand(
            ds_dir(wildcards) / "{array_name}",
            array_name=[
                "variant_bad_ancestral_mask",
                "variant_no_ancestral_allele_mask",
                "variant_not_biallelic_mask",
                "variant_duplicate_position_mask",
                "variant_not_snps_mask",
                "variant_low_quality_ancestral_allele_mask",
                "variant_{region_name}_region_mask",
                "sample_{subset_name}_subset_mask",
            ],
        ),
    output:
        directory(
            data_dir
            / "zarr_vcfs"
            / "chr{chrom_num}"
            / "data.zarr"
            / "variant_{subset_name}_subset_{region_name}_region_{filter_set}_mask"
        ),
    threads: get_resource("combined_mask", "threads")
    resources:
        mem_mb=get_resource("combined_mask", "mem_mb"),
        time_min=get_resource("combined_mask", "time_min"),
        runtime=get_resource("combined_mask", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_combined_mask.py"


rule zarr_stats:
    input:
        lambda wildcards: ds_dir(wildcards) / ".vcf_done",
        lambda wildcards: ds_dir(wildcards)
        / "variant_{subset_name}_subset_{region_name}_region_{filter_set}_mask",
    output:
        data_dir
        / "zarr_stats"
        / "{subset_name}-{region_name}-{filter_set}"
        / "stats.json",
    threads: get_resource("zarr_stats", "threads")
    resources:
        mem_mb=get_resource("zarr_stats", "mem_mb"),
        time_min=get_resource("zarr_stats", "time_min"),
        runtime=get_resource("zarr_stats", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_zarr_stats.py"


checkpoint summary_table:
    input:
        lambda wildcards: [
            data_dir
            / "zarr_stats"
            / f"{wildcards.subset_name}-{region_name}-{wildcards.filter_set}"
            / "stats.json"
            for region_name in config["regions"].keys()
        ],
    output:
        data_dir / "{subset_name}-{filter_set}-region_summary_table.csv",
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/checkpoint_summary_table.py"


rule generate_ancestors:
    input:
        lambda wildcards: ds_dir(wildcards) / ".vcf_done",
        lambda wildcards: ds_dir(wildcards)
        / "variant_{subset_name}_subset_{region_name}_region_{filter_set}_mask",
        lambda wildcards: ds_dir(wildcards) / "sample_{subset_name}_subset_mask",
        data_dir
        / "zarr_stats"
        / "{subset_name}-{region_name}-{filter_set}"
        / "stats.json",
    output:
        data_dir
        / "ancestors"
        / "{subset_name}-{region_name}-{filter_set}"
        / "ancestors.zarr",
    threads: get_resource("generate_ancestors", "threads")
    resources:
        mem_mb=get_resource("generate_ancestors", "mem_mb"),
        time_min=get_resource("generate_ancestors", "time_min"),
        runtime=get_resource("generate_ancestors", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_generate_ancestors.py"


rule truncate_ancestors:
    input:
        data_dir
        / "ancestors"
        / "{subset_name}-{region_name}-{filter_set}"
        / "ancestors.zarr",
    output:
        data_dir
        / "ancestors"
        / "{subset_name}-{region_name}-{filter_set}"
        / "ancestors-truncate-{lower}-{upper}-{multiplier}.zarr",
    threads: get_resource("truncate_ancestors", "threads")
    resources:
        mem_mb=get_resource("truncate_ancestors", "mem_mb"),
        time_min=get_resource("truncate_ancestors", "time_min"),
        runtime=get_resource("truncate_ancestors", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_truncate_ancestors.py"


checkpoint match_ancestors_init:
    input:
        lambda wildcards: ds_dir(wildcards) / ".vcf_done",
        data_dir
        / "ancestors"
        / "{subset_name}-{region_name}-{filter_set}"
        / "ancestors-truncate-{lower}-{upper}-{multiplier}.zarr",
    output:
        data_dir
        / "ancestors_working"
        / "{subset_name}-{region_name}-{filter_set}"
        / "ancestors-truncate-{lower}-{upper}-{multiplier}"
        / "metadata.json",
    threads: get_resource("match_ancestors_init", "threads")
    resources:
        mem_mb=get_resource("match_ancestors_init", "mem_mb"),
        time_min=get_resource("match_ancestors_init", "time_min"),
        runtime=get_resource("match_ancestors_init", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/checkpoint_match_ancestors_init.py"


# Cluster filesystems are slow so cache the ancestor groupings
ancestor_groupings_cache = {}


def ancestor_groupings(checkpoint_output):
    output_path = checkpoint_output.output[0]
    if output_path not in ancestor_groupings_cache:
        with open(output_path, "r") as f:
            md = json.load(f)
            ancestor_groupings_cache[output_path] = md["ancestor_grouping"]
    return ancestor_groupings_cache[output_path]


def num_partitions(checkpoint_output):
    return ancestor_groupings(checkpoint_output)[int(wildcards.group)]["partitions"]


# This function decides if a group should be processed in a single job or partitioned
def match_ancestor_group_input(wildcards):
    checkpoint_output = checkpoints.match_ancestors_init.get(**wildcards)
    match_dir = Path(checkpoint_output.output[0]).parent
    groupings = ancestor_groupings(checkpoint_output)
    group_index = int(wildcards.group)
    partitions = groupings[group_index]["partitions"]
    # Don't use partitions if we are in the first half of the groups, or there are none
    if (
        partitions is not None
        and len(partitions) > get_resource("match_ancestors_group", "threads")
        and group_index > len(groupings) // 2
    ):
        return expand(
            f"{match_dir}/group_{group_index}/partition_" + "{partition}.pkl",
            partition=range(len(partitions)),
            allow_missing=True,
        )

    # This group is small enough to do locally
    # search back until we find a group that requires partitioning, or we reach the start, or we have enough groups
    max_groups = config["match_ancestors"]["max_groups"]
    for i in range(group_index, max(group_index - max_groups, 0), -1):
        if (
            groupings[i]["partitions"] is not None
            and len(groupings[i]["partitions"])
            > get_resource("match_ancestors_group", "threads")
            and i > len(groupings) // 2
        ):
            return match_dir / f"ancestors_{i}.trees"
    if group_index - max_groups > 0:
        return match_dir / f"ancestors_{group_index - max_groups}.trees"
    else:
        return checkpoint_output.output[0]


def match_ancestors_group_num_threads(wildcards):
    input_ = match_ancestor_group_input(wildcards)
    if isinstance(input_, list):
        input_ = input_[0]
    input_ = str(input_)
    # If the input is a pickle file, we are finalising a split group
    if ".pkl" in input_:
        return 1
    # The first group is trivial
    if "metadata.json" in input_:
        first_group = 0
    else:
        first_group = int(re.search(r"ancestors_(\d+).trees", input_).group(1))
    last_group = int(wildcards.group)
    groupings = ancestor_groupings(checkpoints.match_ancestors_init.get(**wildcards))
    most_seen_ancestors = 1
    for i in range(first_group, last_group + 1):
        most_seen_ancestors = max(most_seen_ancestors, len(groupings[i]["ancestors"]))
    return min(most_seen_ancestors, get_resource("match_ancestors_group", "threads"))


def match_ancestors_group_ram(wildcards):
    input_ = match_ancestor_group_input(wildcards)
    if isinstance(input_, list):
        input_ = input_[0]
    if ".pkl" in str(input_):
        # Were just combining results use a small amount
        return get_resource("default", "mem_mb")
    else:
        # Scale the RAM by the number of threads we are running out of the max
        return (
            get_resource("match_ancestors_group", "mem_mb")
            / get_resource("match_ancestors_group", "threads")
        ) * match_ancestors_group_num_threads(wildcards)


rule match_ancestors_group:
    input:
        match_ancestor_group_input,
    output:
        data_dir
        / "ancestors_working"
        / "{subset_name}-{region_name}-{filter_set}"
        / "ancestors-truncate-{lower}-{upper}-{multiplier}"
        / "ancestors_{group}.trees",
    threads: match_ancestors_group_num_threads
    resources:
        mem_mb=match_ancestors_group_ram,
        time_min=get_resource("match_ancestors_group", "time_min"),
        runtime=get_resource("match_ancestors_group", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_match_ancestors_group.py"


rule match_ancestors_group_partition:
    input:
        lambda wildcards: (
            data_dir
            / "ancestors_working"
            / "{subset_name}-{region_name}-{filter_set}"
            / "ancestors-truncate-{lower}-{upper}-{multiplier}"
            / f"ancestors_{int(wildcards.group) - 1}.trees"
        ),
    output:
        data_dir
        / "ancestors_working"
        / "{subset_name}-{region_name}-{filter_set}"
        / "ancestors-truncate-{lower}-{upper}-{multiplier}"
        / "group_{group}"
        / "partition_{partition}.pkl",
    threads: get_resource("match_ancestors_group_partition", "threads")
    resources:
        mem_mb=get_resource("match_ancestors_group_partition", "mem_mb"),
        time_min=get_resource("match_ancestors_group_partition", "time_min"),
        runtime=get_resource("match_ancestors_group_partition", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_match_ancestors_group_partition.py"


def last_ancestor_group(wildcards):
    checkpoint_output = checkpoints.match_ancestors_init.get(**wildcards)
    groupings = ancestor_groupings(checkpoint_output)
    return len(groupings) - 1


rule match_ancestors_final:
    input:
        lambda wildcards: (
            data_dir
            / "ancestors_working"
            / "{subset_name}-{region_name}-{filter_set}"
            / "ancestors-truncate-{lower}-{upper}-{multiplier}"
            / f"ancestors_{last_ancestor_group(wildcards)}.trees"
        ),
    output:
        data_dir
        / "ancestors"
        / "{subset_name}-{region_name}-{filter_set}"
        / "ancestors-truncate-{lower}-{upper}-{multiplier}.trees",
    threads: get_resource("match_ancestors_final", "threads")
    resources:
        mem_mb=get_resource("match_ancestors_final", "mem_mb"),
        time_min=get_resource("match_ancestors_final", "time_min"),
        runtime=get_resource("match_ancestors_final", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_match_ancestors_final.py"


checkpoint match_samples_init:
    input:
        data_dir
        / "ancestors"
        / "{subset_name}-{region_name}-{filter_set}"
        / "ancestors-truncate-{lower}-{upper}-{multiplier}.trees",
        lambda wildcards: ds_dir(wildcards) / ".vcf_done",
        lambda wildcards: ds_dir(wildcards)
        / "variant_{subset_name}_subset_{region_name}_region_{filter_set}_mask",
        lambda wildcards: ds_dir(wildcards) / "sample_{subset_name}_subset_mask",
        lambda wildcards: config["recomb_map"].format(
            chrom=parse_region(config["regions"][wildcards.region_name])[0]
        ),
    output:
        data_dir
        / "samples_working"
        / "{subset_name}-{region_name}-{filter_set}-truncate-{lower}-{upper}-{multiplier}-mm{mismatch}"
        / "metadata.json",
    threads: get_resource("match_samples_init", "threads")
    resources:
        mem_mb=get_resource("match_samples_init", "mem_mb"),
        time_min=get_resource("match_samples_init", "time_min"),
        runtime=get_resource("match_samples_init", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/checkpoint_match_samples_init.py"


def get_sample_partitions(wildcards):
    checkpoint_output = checkpoints.match_samples_init.get(**wildcards)
    with open(checkpoint_output.output[0], "r") as f:
        md = json.load(f)
    return md["num_partitions"]


rule match_sample_partitions:
    input:
        data_dir
        / "samples_working"
        / "{subset_name}-{region_name}-{filter_set}-truncate-{lower}-{upper}-{multiplier}-mm{mismatch}"
        / "metadata.json",
    output:
        data_dir
        / "samples_working"
        / "{subset_name}-{region_name}-{filter_set}-truncate-{lower}-{upper}-{multiplier}-mm{mismatch}"
        / "partition_{partition}.pkl",
    threads: get_resource("match_sample_paths", "threads")
    resources:
        mem_mb=get_resource("match_sample_paths", "mem_mb"),
        time_min=get_resource("match_sample_paths", "time_min"),
        runtime=get_resource("match_sample_paths", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_match_sample_partitions.py"


rule match_samples_finalise:
    input:
        lambda wildcards: expand(
            data_dir
            / "samples_working"
            / "{subset_name}-{region_name}-{filter_set}-truncate-{lower}-{upper}-{multiplier}-mm{mismatch}"
            / "partition_{partition}.pkl",
            partition=range(get_sample_partitions(wildcards)),
            **wildcards,
        ),
    output:
        data_dir
        / "trees"
        / "{subset_name}-{region_name}-{filter_set}"
        / "{subset_name}-{region_name}-{filter_set}-truncate-{lower}-{upper}-{multiplier}-mm{mismatch}-raw.trees",
    threads: get_resource("match_samples", "threads")
    resources:
        mem_mb=get_resource("match_samples", "mem_mb"),
        time_min=get_resource("match_samples", "time_min"),
        runtime=get_resource("match_samples", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_match_samples_finalise.py"


rule post_process:
    input:
        data_dir
        / "trees"
        / "{subset_name}-{region_name}-{filter_set}"
        / "{subset_name}-{region_name}-{filter_set}-truncate-{lower}-{upper}-{multiplier}-mm{mismatch}-raw.trees",
    output:
        data_dir
        / "trees"
        / "{subset_name}-{region_name}-{filter_set}"
        / "{subset_name}-{region_name}-{filter_set}-truncate-{lower}-{upper}-{multiplier}-mm{mismatch}-post-processed.trees",
    threads: get_resource("post_process", "threads")
    resources:
        mem_mb=get_resource("post_process", "mem_mb"),
        time_min=get_resource("post_process", "time_min"),
        runtime=get_resource("post_process", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_post_process.py"


rule full_simplify:
    input:
        data_dir
        / "trees"
        / "{subset_name}-{region_name}-{filter_set}"
        / "{subset_name}-{region_name}-{filter_set}-truncate-{lower}-{upper}-{multiplier}-mm{mismatch}-post-processed.trees",
    output:
        data_dir
        / "trees"
        / "{subset_name}-{region_name}-{filter_set}"
        / "{subset_name}-{region_name}-{filter_set}-truncate-{lower}-{upper}-{multiplier}-mm{mismatch}-post-processed-simplified.trees",
    threads: get_resource("full_simplify", "threads")
    resources:
        mem_mb=get_resource("full_simplify", "mem_mb"),
        time_min=get_resource("full_simplify", "time_min"),
        runtime=get_resource("full_simplify", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_full_simplify.py"


rule split_disjoint_nodes:
    input:
        data_dir
        / "trees"
        / "{subset_name}-{region_name}-{filter_set}"
        / "{subset_name}-{region_name}-{filter_set}-truncate-{lower}-{upper}-{multiplier}-mm{mismatch}-post-processed-simplified.trees",
    output:
        data_dir
        / "trees"
        / "{subset_name}-{region_name}-{filter_set}"
        / "{subset_name}-{region_name}-{filter_set}-truncate-{lower}-{upper}-{multiplier}-mm{mismatch}-post-processed-simplified-SDN.trees",
    threads: get_resource("split_disjoint_nodes", "threads")
    resources:
        mem_mb=get_resource("split_disjoint_nodes", "mem_mb"),
        time_min=get_resource("split_disjoint_nodes", "time_min"),
        runtime=get_resource("split_disjoint_nodes", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_split_disjoint_nodes.py"


rule tsdate:
    input:
        data_dir
        / "trees"
        / "{subset_name}-{region_name}-{filter_set}"
        / "{subset_name}-{region_name}-{filter_set}-truncate-{lower}-{upper}-{multiplier}-mm{mismatch}-post-processed-simplified-SDN.trees",
    output:
        data_dir
        / "trees"
        / "{subset_name}-{region_name}-{filter_set}"
        / "{subset_name}-{region_name}-{filter_set}-truncate-{lower}-{upper}-{multiplier}-mm{mismatch}-post-processed-simplified-SDN-dated-{mut_rate}.trees",
    threads: get_resource("tsdate", "threads")
    resources:
        mem_mb=get_resource("tsdate", "mem_mb"),
        time_min=get_resource("tsdate", "time_min"),
        runtime=get_resource("tsdate", "time_min"),
    conda:
        "tskit_reqs.yaml"
    script:
        "scripts/rule_tsdate.py"
